server:
  port: 7001

eureka:
  instance:
    #eureka的hostname
    hostname: eureka7001.com
  client:
    #false 表示不向注册中心注册自己
    register-with-eureka: false
    #false 表示自己端就是服务中心，为了维护服务实例，不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务地址 三台互相交互在后面加上“,”继续写
      defaultZone: http://eureka7002.com:7002/eureka/
      #单机模式
#      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    #关闭eureka的自我保护机制
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
